language: node_js
node_js:
  - 10.19.0 # Versión en mi PC
  - 12.19.0 # La de mi contenedor
  - 15.1.0  # Última versión del lenguaje

before_install:
  - npm install -g gulp

install:
 - npm install

script:  
 - gulp test
 - gulp firebasedeploy
