language: node_js

node_js:
  - 12

before_install:
  - npm install -g gulp

before_script:
  - npm install -g firebase-tools

install:
 - npm install
 - npm install eslint

script:  
 - gulp test
 - firebase deploy --token $FIREBASE_TOKEN