language: node_js

node_js:
  - 12

before_install:
  - npm install -g gulp

before_script:
  - npm install -g firebase-tools

install:
 - npm install

script:  
 - gulp test

 after_success:
  - firebase deploy --token $FIREBASE_TOKEN