language: node_js

node_js:
  - 12

before_install:
  - npm install -g gulp

before_script:
  - npm install -g firebase-tools
  - npm install -g eslint
  - npm install eslint-plugin-promise@latest --save-dev

install:
 - npm install

script:  
 - gulp test
 - firebase deploy --token $FIREBASE_TOKEN